#?
#? VS Code REST Client extension 
#?

#################################################


@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}


#################################################


@userid = 09981b01-029b-4a4b-bf5d-684f1b984325
@artistid = 60da35d9-ccbb-4c3e-baf6-121a7cb431eb
@trackid = 44a3a027-7413-44f1-afff-fbd27396b318
@albumid = f7990b3f-726e-460a-82bc-57b13e211772

@accesstoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1YzEwNzI0LTIxNGQtNGRiNi05NDNkLTMzNzVhMjczNWYyMCIsImxvZ2luIjoiVXNlcjEiLCJpYXQiOjE2OTI2MDcwMTMsImV4cCI6MTY5MjYwNzA0M30.JRQQOz3ZbU-gjb75_wCrDoc2A9JTK1z67unDrnhNdVI

@refreshtoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1YzEwNzI0LTIxNGQtNGRiNi05NDNkLTMzNzVhMjczNWYyMCIsImxvZ2luIjoiVXNlcjEiLCJpYXQiOjE2OTI2MDcwMTMsImV4cCI6MTY5MjY5MzQxM30.TyyxiHwEZGSVQllgAx6Fulqt3y7cTFVWqhDiDvuccpE
#################################################
##################### AUTH ######################
#################################################

#
# /auth
#


#
### /signup
#
POST http://{{host}}/auth/signup HTTP/1.1
Content-Type: application/json

{
  "login": "User1",
  "password": "passsssss"
}


#
### /login
#
POST http://{{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "login": "User1",
  "password": "passsssss"
}

#
### /refresh
#
POST http://{{host}}/auth/refresh HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshtoken}}"
}



#################################################
##################### USERS #####################
#################################################

#
# /user
#

#
### getAllUsers
#
GET http://{{host}}/user HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
### createUser
#
POST http://{{host}}/user HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "login": "aaaaaaaa",
  "password": "aaaaaaaa"
}

#
### getUserById
#
GET http://{{host}}/user/{{userid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
### updateUserById
#
PUT http://{{host}}/user/{{userid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "oldPassword": "aaaaaaa",
  "newPassword": "aaaaaa"
}

#
### deleteUserById
#
DELETE  http://{{host}}/user/{{userid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#################################################
#################### ARTISTS ####################
#################################################

#
# /artist
#

#
### getAllArtists
#
GET http://{{host}}/artist HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
### createArtist
#
POST http://{{host}}/artist HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "name": "Test Artist",
  "grammy": false
}

#
### getArtistById
#
GET http://{{host}}/artist/{{artistid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#
### updateArtistById
#
PUT http://{{host}}/artist/{{artistid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "grammy": true
}

#
### deleteArtistById
#
DELETE  http://{{host}}/artist/{{artistid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#################################################
#################### TRACKS #####################
#################################################

#
# /track
#

#
### getAllTracks
#
GET http://{{host}}/track HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
### createTrack
#
POST http://{{host}}/track HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "name": "aaaa",
  "artistId": "{{artistid}}",
  "albumId": null,
  "duration": 200
}

#
### getTrackById
#
GET http://{{host}}/track/{{trackid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
### updateTrackById
#
PUT http://{{host}}/track/{{trackid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "name": "bbbbb"
}

#
### deleteTrackById
#
DELETE  http://{{host}}/track/{{trackid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#################################################
#################### ALBUMS #####################
#################################################

#
# /album
#


#
# getAllAlbums
#
GET http://{{host}}/album HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
# createAlbum
#
POST http://{{host}}/album HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "name": "Innuendo",
  "year": 1999,
  "artistId": "{{artistid}}"
}

#
# getAlbumById
#
GET http://{{host}}/album/{{albumid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
# UpdateAlbumById
#
PUT http://{{host}}/album/{{albumid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "grammy": true
}

#
# deleteAlbumById
#
DELETE  http://{{host}}/album/{{albumid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#################################################
################## FAVORITES ####################
#################################################

#
# /favs
#

#
# getAllFavorites
#
GET http://{{host}}/favs HTTP/1.1
Authorization: Bearer {{accesstoken}}


#
# addTrackToFavorites
#
POST http://{{host}}/favs/track/4317cb57-9170-446e-a5dd-bcb8741b6119 HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
# deleteTrackFromFavorites
#
DELETE  http://{{host}}/favs/track/{{trackid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#
# addAlbumToFavorites
#
POST http://{{host}}/favs/album/{{albumid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
# deleteAlbumFromFavorites
#
DELETE  http://{{host}}/favs/album/{{albumid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


#
# addArtistToFavorites
#
POST http://{{host}}/favs/artist/{{artistid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

#
# deleteArtistFromFavorites
#
DELETE  http://{{host}}/favs/artist/{{artistid}} HTTP/1.1
Authorization: Bearer {{accesstoken}}


